const today = new Date();
const sevenDateLater = new Date(today.setDate(today.getDate() + 7));
export default {
  cars: ["1", "3"],
  page: 1,
  limit: 12,
  startDateTime: new Date(),
  endDateTime: sevenDateLater,
  typeOfCars: [
    "Mini",
    "Sedan",
    "Hatchback",
    "Convertible",
    "Jeep",
    "Limousine ",
    "Minivan",
    "Sports ",
  ],
  filters: {},
  autoMakers: [
    "BMW",
    "Ford",
    "Volkswagen AG",
    "Toyota",
    "Stellantis",
    "Mercedes-Benz",
    "Honda",
    "Hyundai",
  ],
  sortOptions: [
    "Giá thấp nhất",
    "Giá cao nhất",
    "Đánh giá tốt nhất",
    "Giảm giá nhiều nhất",
  ],
  location: {
    compound: {
      province: "Hồ Chí Minh",
    },
  },
  features: [
    "Bản đồ",
    "Camera cập lề",
    "Cảm biến lốp",
    "Cửa sổ trời",
    "Khe cắm USB",
    "Màn hình Android",
    "Bluetooth",
    "Camera hành trình",
    "Cảm biến va chạm",
    "Định vị GPS",
    "Lốp dự phòng",
    "ETC",
    "Camera 360",
    "Camera Lùi",
    "Cảnh báo tốc độ",
    "Ghế trẻ em",
    "Màn hình DVD",
    "Túi khí an toàn",
  ],
  fuels: ["Xăng", "Dầu Diesel", "Điện"],
  transmissions: ["Số tự động", "Số sàn"],
  yearRangeValue: [
    2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
    2017, 2018, 2019, 2020, 2021, 2022, 2023,
  ],
  filterState: {},
  carRegistration: {},
};
