const today = new Date();
const sevenDateLater = new Date(today.setDate(today.getDate() + 7));
export default {
  cars: ["1", "3"],
  page: 1,
  limit: 12,
  startDateTime: today,
  endDateTime: sevenDateLater,
  typeOfCars: ["Mini", "Sedan", "Hatchback", "Gầm cao"],
  filters: {},
  autoMakers: [
    "BMW",
    "Ford",
    "Volkswagen AG",
    "Toyota",
    "Stellantis",
    "Mercedes-Benz",
    "Honda",
    "Hyundai",
  ],
  sortOptions: [
    "Giá thấp nhất",
    "Giá cao nhất",
    "Đánh giá tốt nhất",
    "Giảm giá nhiều nhất",
  ],
  location: {},
  features: [
    "Bản đồ",
    "Camera cập lề",
    "Cảm biến lốp",
    "Cửa sổ trời",
    "Khe cắm USB",
    "Màn hình Android",
    "Bluetooth",
    "Camera hành trình",
    "Cảm biến va chạm",
    "Định vị GPS",
    "Lốp dự phòng",
    "ETC",
    "Camera 360",
    "Camera Lùi",
    "Cảnh báo tốc độ",
    "Ghế trẻ em",
    "Màn hình DVD",
    "Túi khí an toàn",
  ],
  fuels: ["Tất cả", "Xăng", "Dầu Diesel", "Điện"],
};
