version: "3"
services:
  nginx:
    image: nginx
    container_name: rebo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    container_name: rebocars-server1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  app2:
    container_name: rebocars-server2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db

  app3:
    container_name: rebocars-server3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - db  

  db:
    image: mongo
    container_name: rebo-mongo
    ports:
      - "27017:27017"
